export type UkCompetitorSeed = {
  companyName: string;
  website: string;
  services: string;
  lastRevenue: string;
  notes: string;
  sortOrder: number;
};

export const UK_COMPETITOR_SEEDS: UkCompetitorSeed[] = [
  {
    companyName: "Critical Asset",
    website: "https://criticalasset.co.uk/",
    services: "Building, roof, solar, and industrial asset inspection with thermal and visual reporting.",
    lastRevenue: "£3.2M (2024 est.)",
    notes: "Strong insurer and logistics park footprint across England.",
    sortOrder: 1,
  },
  {
    companyName: "Cyberhawk",
    website: "https://thecyberhawk.com/",
    services: "Oil & gas, utilities, and industrial visual and thermal inspection programmes.",
    lastRevenue: "£18M (2023)",
    notes: "Global operator with major UK energy sector contracts.",
    sortOrder: 2,
  },
  {
    companyName: "Consortiq",
    website: "https://consortiq.com/",
    services: "Operational consultancy, PfCO/CAA training, fleet setup, and compliance support.",
    lastRevenue: "£4.5M (2024 est.)",
    notes: "Consultancy-led model with enterprise and public-sector clients.",
    sortOrder: 3,
  },
  {
    companyName: "Coptrz",
    website: "https://coptrz.com/",
    services: "Enterprise drone hardware, payloads, training, and managed survey workflows.",
    lastRevenue: "£12M (2023)",
    notes: "DJI enterprise channel partner with strong construction pipeline.",
    sortOrder: 4,
  },
  {
    companyName: "Heliguy",
    website: "https://www.heliguy.com/",
    services: "Drone sales, repairs, training, and in-house inspection/media delivery teams.",
    lastRevenue: "£9M (2024 est.)",
    notes: "North-east base with national enterprise support desk.",
    sortOrder: 5,
  },
  {
    companyName: "RUAS",
    website: "https://www.ruas.co.uk/",
    services: "CAA-approved training, operational support, and specialist inspection services.",
    lastRevenue: "£2.1M (2024 est.)",
    notes: "Training academy model with recurring operator upskilling revenue.",
    sortOrder: 6,
  },
  {
    companyName: "iRed",
    website: "https://ired.co.uk/",
    services: "Thermal roof, solar, and building envelope inspections for FM and insurers.",
    lastRevenue: "£1.8M (2024 est.)",
    notes: "Thermal-first positioning with strong insurance referral network.",
    sortOrder: 7,
  },
  {
    companyName: "Plowman Craven",
    website: "https://www.plowmancraven.co.uk/",
    services: "Measured building surveys, BIM capture, and heritage drone photogrammetry.",
    lastRevenue: "£22M (2023)",
    notes: "Established surveying brand adding drone capture to traditional workflows.",
    sortOrder: 8,
  },
  {
    companyName: "Terra Drone UK",
    website: "https://www.terradrone.net/",
    services: "Topographic survey, LiDAR, inspection, and digital twin deliverables.",
    lastRevenue: "£6M (2024 est.)",
    notes: "Part of wider Terra Drone group with utility and infrastructure focus.",
    sortOrder: 9,
  },
  {
    companyName: "Balmore Aerial Services",
    website: "https://balmore.co.uk/",
    services: "Roof surveys, thermal imaging, and aerial photography for commercial estates.",
    lastRevenue: "£950K (2024 est.)",
    notes: "Scotland-heavy client base expanding into northern England.",
    sortOrder: 10,
  },
  {
    companyName: "Halo Photogrammetry",
    website: "https://halophotogrammetry.com/",
    services: "High-accuracy 3D models, orthomosaics, and progress monitoring for construction.",
    lastRevenue: "£1.4M (2024 est.)",
    notes: "Construction progress and heritage documentation specialist.",
    sortOrder: 11,
  },
  {
    companyName: "OpenWorks Engineering",
    website: "https://openworksengineering.com/",
    services: "Critical infrastructure inspection, confined-space alternatives, and data analytics.",
    lastRevenue: "£3.8M (2024 est.)",
    notes: "Infrastructure and transport sector repeat contracts.",
    sortOrder: 12,
  },
  {
    companyName: "Inspect Air",
    website: "https://inspectair.co.uk/",
    services: "Roof, chimney, and building fabric inspections for housing associations.",
    lastRevenue: "£720K (2024 est.)",
    notes: "Social housing and FM maintenance programmes.",
    sortOrder: 13,
  },
  {
    companyName: "Drone Major Group",
    website: "https://www.dronemajor.co.uk/",
    services: "Strategy, procurement, and managed drone programmes for enterprise clients.",
    lastRevenue: "£2.6M (2024 est.)",
    notes: "Advisory-led with public sector and defence adjacency.",
    sortOrder: 14,
  },
  {
    companyName: "Urban Vision",
    website: "https://www.urbanvision.co.uk/",
    services: "Aerial filming, property marketing, and city-scale visual capture.",
    lastRevenue: "£1.1M (2024 est.)",
    notes: "London-centric media and real-estate positioning.",
    sortOrder: 15,
  },
  {
    companyName: "GeoSky Surveys",
    website: "https://www.geoskysurveys.co.uk/",
    services: "Topographic surveys, volumetrics, and quarry/stockpile analytics.",
    lastRevenue: "£890K (2024 est.)",
    notes: "Quarry and earthworks monitoring in Midlands and south.",
    sortOrder: 16,
  },
  {
    companyName: "Skyhook Services",
    website: "https://skyhookservices.co.uk/",
    services: "Mast, tower, and telecom infrastructure inspection with RTK workflows.",
    lastRevenue: "£640K (2024 est.)",
    notes: "Telecoms and utilities niche with repeat tower portfolio work.",
    sortOrder: 17,
  },
  {
    companyName: "Aerial CM",
    website: "https://www.aerialcm.co.uk/",
    services: "Construction site progress, 4D sequencing support, and stakeholder reporting.",
    lastRevenue: "£1.3M (2024 est.)",
    notes: "Tier-1 contractor preferred supplier lists in London and south-east.",
    sortOrder: 18,
  },
  {
    companyName: "LM Survey Partnership",
    website: "https://www.lmgroup.co.uk/",
    services: "Land surveying, drone LiDAR, and cadastral support for developers.",
    lastRevenue: "£5.5M (2023)",
    notes: "Traditional survey firm with growing UAV capture division.",
    sortOrder: 19,
  },
  {
    companyName: "Nationwide Drones",
    website: "https://www.nationwide-drones.co.uk/",
    services: "Nationwide inspection, surveying, and emergency response drone deployments.",
    lastRevenue: "£2.0M (2024 est.)",
    notes: "Multi-region operator bidding on framework contracts.",
    sortOrder: 20,
  },
];
