export type MiningCountry = "spain" | "uk" | "portugal" | "kenya";

export type MineOperator = {
  id: string;
  rank: number;
  companyName: string;
  primaryCommodity: string;
  annualRevenueUsdM: number;
  employees: number;
  headquarters: string;
  siteLabel: string;
  latitude: number;
  longitude: number;
  droneProviders: string[];
};

export type MiningCountryMeta = {
  id: MiningCountry;
  label: string;
  mapCenter: [number, number];
  mapZoom: number;
  /** Active open-pit, underground, and large quarry sites suited to drone survey/inspection. */
  sizeableMineSites: number;
  siteBreakdown: string;
};

export const MINING_COUNTRIES: readonly MiningCountryMeta[] = [
  {
    id: "spain",
    label: "Spain",
    mapCenter: [40.2, -3.5],
    mapZoom: 6,
    sizeableMineSites: 42,
    siteBreakdown: "14 metal · 9 aggregates · 19 mixed industrial",
  },
  {
    id: "uk",
    label: "UK",
    mapCenter: [54.5, -2.5],
    mapZoom: 6,
    sizeableMineSites: 56,
    siteBreakdown: "3 metal/industrial · 38 quarry · 15 cement/kaolin",
  },
  {
    id: "portugal",
    label: "Portugal",
    mapCenter: [39.5, -8.0],
    mapZoom: 7,
    sizeableMineSites: 24,
    siteBreakdown: "8 metal · 6 tungsten/tin · 10 quarry/cement",
  },
  {
    id: "kenya",
    label: "Kenya",
    mapCenter: [0.2, 37.5],
    mapZoom: 6,
    sizeableMineSites: 19,
    siteBreakdown: "6 mineral sands/soda · 7 gold · 6 quarry/cement",
  },
] as const;

const SPAIN_OPERATORS: MineOperator[] = [
  {
    id: "es-matsa",
    rank: 1,
    companyName: "MATSA (Matsa Resources)",
    primaryCommodity: "Copper / Zinc",
    annualRevenueUsdM: 820,
    employees: 1850,
    headquarters: "Huelva, Andalusia",
    siteLabel: "Aguas Teñidas · Sotiel · Magdalena",
    latitude: 37.694,
    longitude: -6.593,
    droneProviders: ["DJI Enterprise", "Wingtra", "DroneDeploy"],
  },
  {
    id: "es-las-cruces",
    rank: 2,
    companyName: "Cobre Las Cruces (First Quantum)",
    primaryCommodity: "Copper",
    annualRevenueUsdM: 640,
    employees: 920,
    headquarters: "Gerena, Seville",
    siteLabel: "Las Cruces open pit",
    latitude: 37.522,
    longitude: -6.155,
    droneProviders: ["DJI Enterprise", "senseFly", "Delair"],
  },
  {
    id: "es-atalaya",
    rank: 3,
    companyName: "Atalaya Mining",
    primaryCommodity: "Copper",
    annualRevenueUsdM: 410,
    employees: 640,
    headquarters: "Huelva, Andalusia",
    siteLabel: "Riotinto-Tinto complex",
    latitude: 37.694,
    longitude: -6.593,
    droneProviders: ["DJI Enterprise", "Wingtra"],
  },
  {
    id: "es-asturiana",
    rank: 4,
    companyName: "Asturiana de Zinc (Glencore)",
    primaryCommodity: "Zinc / Lead",
    annualRevenueUsdM: 360,
    employees: 780,
    headquarters: "Arnao, Asturias",
    siteLabel: "Arnao smelter complex",
    latitude: 43.402,
    longitude: -5.821,
    droneProviders: ["DJI Enterprise", "Flyability", "Microdrones"],
  },
  {
    id: "es-berkeley",
    rank: 5,
    companyName: "Berkeley Energia",
    primaryCommodity: "Uranium",
    annualRevenueUsdM: 125,
    employees: 210,
    headquarters: "Salamanca",
    siteLabel: "Retortillo-Santidad project",
    latitude: 41.452,
    longitude: -5.578,
    droneProviders: ["senseFly", "DJI Enterprise"],
  },
  {
    id: "es-orvana",
    rank: 6,
    companyName: "Orvana Minerals",
    primaryCommodity: "Copper / Gold",
    annualRevenueUsdM: 185,
    employees: 420,
    headquarters: "Asturias",
    siteLabel: "El Valle · Carlés mines",
    latitude: 43.158,
    longitude: -5.967,
    droneProviders: ["DJI Enterprise", "DroneDeploy"],
  },
  {
    id: "es-los-santos",
    rank: 7,
    companyName: "Los Santos (Almonty)",
    primaryCommodity: "Tungsten",
    annualRevenueUsdM: 95,
    employees: 280,
    headquarters: "Salamanca",
    siteLabel: "Los Santos scheelite mine",
    latitude: 41.983,
    longitude: -6.867,
    droneProviders: ["Wingtra", "DJI Enterprise"],
  },
  {
    id: "es-saloro",
    rank: 8,
    companyName: "Saloro (Priority Zinc)",
    primaryCommodity: "Tungsten",
    annualRevenueUsdM: 82,
    employees: 190,
    headquarters: "Ciudad Real",
    siteLabel: "Barruecopardo mine",
    latitude: 41.067,
    longitude: -6.683,
    droneProviders: ["senseFly", "DJI Enterprise"],
  },
  {
    id: "es-sotkamo",
    rank: 9,
    companyName: "Sotkamo Silver",
    primaryCommodity: "Silver",
    annualRevenueUsdM: 48,
    employees: 95,
    headquarters: "Finland / Spanish ops",
    siteLabel: "Silver Crown project",
    latitude: 40.416,
    longitude: -3.703,
    droneProviders: ["DJI Enterprise"],
  },
  {
    id: "es-el-astillero",
    rank: 10,
    companyName: "El Valle-Boinás (Orvana JV legacy)",
    primaryCommodity: "Copper / Gold",
    annualRevenueUsdM: 72,
    employees: 160,
    headquarters: "Asturias",
    siteLabel: "Boinás-Carles belt",
    latitude: 43.142,
    longitude: -5.912,
    droneProviders: ["DJI Enterprise", "Delair"],
  },
];

const UK_OPERATORS: MineOperator[] = [
  {
    id: "uk-glencore",
    rank: 1,
    companyName: "Glencore",
    primaryCommodity: "Diversified",
    annualRevenueUsdM: 255_000,
    employees: 150_000,
    headquarters: "London, UK",
    siteLabel: "UK corporate HQ · global portfolio",
    latitude: 51.507,
    longitude: -0.128,
    droneProviders: ["DJI Enterprise", "Wingtra", "Flyability", "Delair"],
  },
  {
    id: "uk-anglo",
    rank: 2,
    companyName: "Anglo American",
    primaryCommodity: "Diversified",
    annualRevenueUsdM: 30_700,
    employees: 55_000,
    headquarters: "London, UK",
    siteLabel: "Woodsmith polyhalite (Yorkshire)",
    latitude: 54.558,
    longitude: -0.687,
    droneProviders: ["DJI Enterprise", "senseFly", "DroneDeploy"],
  },
  {
    id: "uk-rio-tinto",
    rank: 3,
    companyName: "Rio Tinto",
    primaryCommodity: "Iron / Copper",
    annualRevenueUsdM: 54_000,
    employees: 57_000,
    headquarters: "London, UK",
    siteLabel: "London listing · global ops",
    latitude: 51.503,
    longitude: -0.084,
    droneProviders: ["DJI Enterprise", "Wingtra", "Microdrones"],
  },
  {
    id: "uk-bhp",
    rank: 4,
    companyName: "BHP Group",
    primaryCommodity: "Diversified",
    annualRevenueUsdM: 56_000,
    employees: 80_000,
    headquarters: "London, UK",
    siteLabel: "Dual-listed HQ",
    latitude: 51.512,
    longitude: -0.091,
    droneProviders: ["DJI Enterprise", "Delair", "senseFly"],
  },
  {
    id: "uk-antofagasta",
    rank: 5,
    companyName: "Antofagasta",
    primaryCommodity: "Copper",
    annualRevenueUsdM: 6_400,
    employees: 19_000,
    headquarters: "London, UK",
    siteLabel: "London HQ · Los Pelambres (Chile)",
    latitude: 51.509,
    longitude: -0.134,
    droneProviders: ["DJI Enterprise", "Wingtra"],
  },
  {
    id: "uk-fresnillo",
    rank: 6,
    companyName: "Fresnillo",
    primaryCommodity: "Silver / Gold",
    annualRevenueUsdM: 2_300,
    employees: 8_500,
    headquarters: "London, UK",
    siteLabel: "London HQ · Mexico operations",
    latitude: 51.515,
    longitude: -0.142,
    droneProviders: ["DJI Enterprise", "senseFly"],
  },
  {
    id: "uk-hochschild",
    rank: 7,
    companyName: "Hochschild Mining",
    primaryCommodity: "Silver / Gold",
    annualRevenueUsdM: 890,
    employees: 4_200,
    headquarters: "London, UK",
    siteLabel: "London HQ · Americas portfolio",
    latitude: 51.498,
    longitude: -0.105,
    droneProviders: ["DJI Enterprise", "Flyability"],
  },
  {
    id: "uk-cornish-lithium",
    rank: 8,
    companyName: "Cornish Lithium",
    primaryCommodity: "Lithium",
    annualRevenueUsdM: 42,
    employees: 85,
    headquarters: "Cornwall, UK",
    siteLabel: "United Downs geothermal lithium",
    latitude: 50.228,
    longitude: -5.168,
    droneProviders: ["DJI Enterprise", "Wingtra"],
  },
  {
    id: "uk-imerys",
    rank: 9,
    companyName: "Imerys (UK Kaolin)",
    primaryCommodity: "Kaolin / Minerals",
    annualRevenueUsdM: 520,
    employees: 1_100,
    headquarters: "Cornwall, UK",
    siteLabel: "Lee Moor · Par china clay",
    latitude: 50.412,
    longitude: -4.102,
    droneProviders: ["DJI Enterprise", "DroneDeploy", "Delair"],
  },
  {
    id: "uk-boulby",
    rank: 10,
    companyName: "ICL Boulby",
    primaryCommodity: "Potash / Polyhalite",
    annualRevenueUsdM: 310,
    employees: 650,
    headquarters: "North Yorkshire, UK",
    siteLabel: "Boulby underground mine",
    latitude: 54.558,
    longitude: -0.812,
    droneProviders: ["Flyability", "DJI Enterprise"],
  },
];

const PORTUGAL_OPERATORS: MineOperator[] = [
  {
    id: "pt-lundin",
    rank: 1,
    companyName: "Lundin Mining (Somincor)",
    primaryCommodity: "Copper / Zinc",
    annualRevenueUsdM: 2_800,
    employees: 1_050,
    headquarters: "Castro Verde, Alentejo",
    siteLabel: "Neves-Corvo mine",
    latitude: 37.957,
    longitude: -7.965,
    droneProviders: ["DJI Enterprise", "Wingtra", "Flyability"],
  },
  {
    id: "pt-almina",
    rank: 2,
    companyName: "Almina (Aljustrel)",
    primaryCommodity: "Copper / Zinc / Lead",
    annualRevenueUsdM: 420,
    employees: 680,
    headquarters: "Aljustrel, Alentejo",
    siteLabel: "Aljustrel pyrite belt",
    latitude: 37.893,
    longitude: -8.165,
    droneProviders: ["DJI Enterprise", "senseFly"],
  },
  {
    id: "pt-panasqueira",
    rank: 3,
    companyName: "Panasqueira Mines",
    primaryCommodity: "Tungsten / Tin",
    annualRevenueUsdM: 185,
    employees: 320,
    headquarters: "Covilhã, Castelo Branco",
    siteLabel: "Panasqueira underground",
    latitude: 40.167,
    longitude: -7.867,
    droneProviders: ["Flyability", "DJI Enterprise"],
  },
  {
    id: "pt-lousal",
    rank: 4,
    companyName: "Lousal Mine (Sovranas)",
    primaryCommodity: "Copper / Zinc",
    annualRevenueUsdM: 95,
    employees: 180,
    headquarters: "Grândola, Alentejo",
    siteLabel: "Lousal historic complex",
    latitude: 38.067,
    longitude: -8.483,
    droneProviders: ["DJI Enterprise", "DroneDeploy"],
  },
  {
    id: "pt-secil",
    rank: 5,
    companyName: "Secil-Outão",
    primaryCommodity: "Limestone / Cement",
    annualRevenueUsdM: 380,
    employees: 520,
    headquarters: "Setúbal",
    siteLabel: "Outão quarry",
    latitude: 38.518,
    longitude: -8.902,
    droneProviders: ["DJI Enterprise", "Wingtra", "Delair"],
  },
  {
    id: "pt-mota",
    rank: 6,
    companyName: "Grupo Mota",
    primaryCommodity: "Aggregates / Quarrying",
    annualRevenueUsdM: 1_200,
    employees: 3_400,
    headquarters: "Porto",
    siteLabel: "National quarry network",
    latitude: 41.158,
    longitude: -8.629,
    droneProviders: ["DJI Enterprise", "DroneDeploy"],
  },
  {
    id: "pt-iberian",
    rank: 7,
    companyName: "Iberian Resources",
    primaryCommodity: "Gold / Copper",
    annualRevenueUsdM: 78,
    employees: 140,
    headquarters: "Montemor-o-Novo",
    siteLabel: "Alentejo exploration belt",
    latitude: 38.648,
    longitude: -8.214,
    droneProviders: ["senseFly", "DJI Enterprise"],
  },
  {
    id: "pt-rio-tinto",
    rank: 8,
    companyName: "Aethel Mining",
    primaryCommodity: "Copper",
    annualRevenueUsdM: 62,
    employees: 95,
    headquarters: "Alentejo",
    siteLabel: "São Domingos historic district",
    latitude: 37.638,
    longitude: -7.498,
    droneProviders: ["DJI Enterprise", "Wingtra"],
  },
  {
    id: "pt-savin",
    rank: 9,
    companyName: "Savin Resources",
    primaryCommodity: "Tungsten / Tin",
    annualRevenueUsdM: 55,
    employees: 75,
    headquarters: "Castelo Branco",
    siteLabel: "Tabuaço tungsten project",
    latitude: 41.112,
    longitude: -7.567,
    droneProviders: ["DJI Enterprise"],
  },
  {
    id: "pt-avocet",
    rank: 10,
    companyName: "Avocet Mining (Talavera)",
    primaryCommodity: "Gold",
    annualRevenueUsdM: 48,
    employees: 110,
    headquarters: "Beja, Alentejo",
    siteLabel: "Talavera gold project",
    latitude: 38.015,
    longitude: -7.865,
    droneProviders: ["senseFly", "DJI Enterprise"],
  },
];

const KENYA_OPERATORS: MineOperator[] = [
  {
    id: "ke-base",
    rank: 1,
    companyName: "Base Titanium (Base Resources)",
    primaryCommodity: "Mineral Sands (Ti)",
    annualRevenueUsdM: 250,
    employees: 1_200,
    headquarters: "Kwale County",
    siteLabel: "Kwale mineral sands mine",
    latitude: -4.312,
    longitude: 39.452,
    droneProviders: ["DJI Enterprise", "Wingtra", "DroneDeploy"],
  },
  {
    id: "ke-magadi",
    rank: 2,
    companyName: "Tata Chemicals Magadi",
    primaryCommodity: "Soda Ash / Trona",
    annualRevenueUsdM: 210,
    employees: 980,
    headquarters: "Kajiado County",
    siteLabel: "Lake Magadi operations",
    latitude: -1.878,
    longitude: 36.268,
    droneProviders: ["DJI Enterprise", "Delair"],
  },
  {
    id: "ke-karebe",
    rank: 3,
    companyName: "Karebe Gold Mining",
    primaryCommodity: "Gold",
    annualRevenueUsdM: 95,
    employees: 420,
    headquarters: "Nandi County",
    siteLabel: "Kilimapesa · Chemase mines",
    latitude: 0.152,
    longitude: 35.012,
    droneProviders: ["DJI Enterprise", "senseFly"],
  },
  {
    id: "ke-fluorspar",
    rank: 4,
    companyName: "Kenya Fluorspar",
    primaryCommodity: "Fluorspar",
    annualRevenueUsdM: 72,
    employees: 280,
    headquarters: "Elgeyo-Marakwet",
    siteLabel: "Kimwarer fluorspar mine",
    latitude: 0.652,
    longitude: 35.518,
    droneProviders: ["DJI Enterprise", "Wingtra"],
  },
  {
    id: "ke-mayfox",
    rank: 5,
    companyName: "Mayfox Mining",
    primaryCommodity: "Gold",
    annualRevenueUsdM: 58,
    employees: 190,
    headquarters: "West Kenya",
    siteLabel: "Siaya gold belt",
    latitude: 0.062,
    longitude: 34.288,
    droneProviders: ["DJI Enterprise"],
  },
  {
    id: "ke-cortec",
    rank: 6,
    companyName: "Cortec Mining Kenya",
    primaryCommodity: "Niobium / Rare Earths",
    annualRevenueUsdM: 45,
    employees: 85,
    headquarters: "Kwale County",
    siteLabel: "Mrima Hill niobium project",
    latitude: -4.385,
    longitude: 39.312,
    droneProviders: ["senseFly", "DJI Enterprise", "DroneDeploy"],
  },
  {
    id: "ke-arm",
    rank: 7,
    companyName: "National Cement (ARM legacy)",
    primaryCommodity: "Limestone / Cement",
    annualRevenueUsdM: 180,
    employees: 650,
    headquarters: "Athi River",
    siteLabel: "Kaloleni · Athi River quarries",
    latitude: -1.452,
    longitude: 36.982,
    droneProviders: ["DJI Enterprise", "Delair"],
  },
  {
    id: "ke-red-rock",
    rank: 8,
    companyName: "Red Rock Resources",
    primaryCommodity: "Gold / Exploration",
    annualRevenueUsdM: 38,
    employees: 65,
    headquarters: "Migori County",
    siteLabel: "Migori gold belt",
    latitude: -1.062,
    longitude: 34.472,
    droneProviders: ["DJI Enterprise", "Wingtra"],
  },
  {
    id: "ke-pacific",
    rank: 9,
    companyName: "Pacific Wildcat (Cortec parent)",
    primaryCommodity: "Rare Earths",
    annualRevenueUsdM: 32,
    employees: 55,
    headquarters: "Nairobi",
    siteLabel: "Coastal rare earth portfolio",
    latitude: -1.286,
    longitude: 36.817,
    droneProviders: ["senseFly", "DJI Enterprise"],
  },
  {
    id: "ke-acacia",
    rank: 10,
    companyName: "Shanta Gold (West Kenya)",
    primaryCommodity: "Gold",
    annualRevenueUsdM: 125,
    employees: 340,
    headquarters: "Kakamega County",
    siteLabel: "Isulu · Bushiangala projects",
    latitude: 0.282,
    longitude: 34.752,
    droneProviders: ["DJI Enterprise", "Flyability", "DroneDeploy"],
  },
];

export const MINING_OPERATORS_BY_COUNTRY: Record<MiningCountry, MineOperator[]> = {
  spain: SPAIN_OPERATORS,
  uk: UK_OPERATORS,
  portugal: PORTUGAL_OPERATORS,
  kenya: KENYA_OPERATORS,
};

export function getMiningCountryMeta(country: MiningCountry): MiningCountryMeta {
  return MINING_COUNTRIES.find((entry) => entry.id === country) ?? MINING_COUNTRIES[0];
}

export function formatMiningRevenue(usdMillions: number): string {
  if (usdMillions >= 1_000) {
    const billions = usdMillions / 1_000;
    return billions >= 100
      ? `$${billions.toFixed(0)}B`
      : `$${billions.toFixed(1)}B`;
  }
  return `$${usdMillions.toFixed(0)}M`;
}

export function formatEmployeeCount(count: number): string {
  if (count >= 1_000) {
    return `${(count / 1_000).toFixed(count >= 10_000 ? 0 : 1)}k`;
  }
  return count.toLocaleString("en-GB");
}
