import type { SectorCountry, SectorCountryProfile, SectorSubSector } from "@/lib/sector-data";

type OrgInput = [name: string, website: string, droneUse: string, detail: string, lat: number, lng: number];

const MAP: Record<SectorCountry, { center: [number, number]; zoom: number }> = {
  spain: { center: [40.2, -3.5], zoom: 6 },
  uk: { center: [54.5, -2.5], zoom: 6 },
  portugal: { center: [39.5, -8.0], zoom: 7 },
  kenya: { center: [0.2, 37.5], zoom: 6 },
};

function orgs(entries: OrgInput[]) {
  return entries.map(([name, website, droneUse, detail, latitude, longitude], index) => ({
    rank: index + 1,
    name,
    website,
    droneUse,
    detail,
    latitude,
    longitude,
  }));
}

function profile(
  country: SectorCountry,
  subSector: SectorSubSector,
  siteCount: number,
  siteLabel: string,
  siteBreakdown: string,
  organizations: OrgInput[],
  servicesOffered: string[],
): SectorCountryProfile {
  const map = MAP[country];
  return {
    country,
    subSector,
    siteCount,
    siteLabel,
    siteBreakdown,
    mapCenter: map.center,
    mapZoom: map.zoom,
    organizations: orgs(organizations),
    servicesOffered,
  };
}

const SOLAR_SERVICES = [
  "PV array inspection and hotspot detection",
  "Construction progress and as-built surveys",
  "Substation and inverter yard mapping",
  "Vegetation encroachment monitoring",
  "Thermal anomaly reporting for O&M teams",
  "Digital twin orthomosaics for asset handover",
];

const CONSTRUCTION_SERVICES = [
  "Site progress and earthworks volume tracking",
  "Highway and bridge structural surveys",
  "4D BIM-ready point clouds and orthophotos",
  "Cut-and-fill analysis for civils packages",
  "Safety and perimeter monitoring",
  "Stakeholder reporting imagery and video",
];

const UTILITIES_SERVICES = [
  "Transmission corridor vegetation mapping",
  "Substation condition and thermal surveys",
  "Pylon and conductor visual inspection",
  "Outage planning and access route surveys",
  "LiDAR-ready corridor capture",
  "Storm damage assessment and response mapping",
];

const RAIL_SERVICES = [
  "Trackbed and embankment monitoring",
  "Earthworks progress for renewals",
  "Station and depot roof inspection",
  "Overhead line equipment visual surveys",
  "Drainage and slope stability mapping",
  "Possession-window rapid capture programs",
];

const INDUSTRIAL_SERVICES = [
  "Flare stack and chimney inspection",
  "Roof and cladding condition surveys",
  "Tank farm and pipe rack visual inspection",
  "Thermal leak detection on process lines",
  "Confined-space and ATEX-zone alternatives",
  "Turnaround progress monitoring",
];

const WAREHOUSE_SERVICES = [
  "Roof condition and leak detection surveys",
  "Large-site security perimeter mapping",
  "Yard and dock logistics layout capture",
  "Solar rooftop potential assessments",
  "Construction and fit-out progress monitoring",
  "Insurance and compliance documentation flights",
];

const AGRICULTURE_SERVICES = [
  "Crop health and NDVI mapping",
  "Irrigation system and drainage surveys",
  "Topographic mapping for land planning",
  "Livestock and boundary monitoring",
  "Erosion and watercourse inspection",
  "Precision agriculture prescription mapping",
];

const SOLAR: Record<SectorCountry, SectorCountryProfile> = {
  spain: profile("spain", "solar-farms", 318, "solar farms", "210 utility · 68 commercial · 40 hybrid", [
    ["Iberdrola Renovables", "iberdrola.com", "DJI Enterprise · DroneDeploy", "Núñez de Balboa 500 MW", 42.12, -4.85],
    ["Endesa X", "endesa.com", "senseFly · DJI Enterprise", "Andalusia PV cluster", 37.39, -5.98],
    ["Acciona Energía", "acciona-energia.com", "Wingtra · DJI Enterprise", "Extremadura solar belt", 39.18, -6.42],
    ["Forestalia Group", "forestalia.es", "DJI Enterprise", "Zaragoza PV portfolio", 41.65, -0.88],
    ["X-Elio", "x-elio.com", "DroneDeploy · DJI", "Castilla-La Mancha sites", 39.86, -3.92],
    ["Solaria", "solariaenergia.com", "senseFly", "Madrid-region trackers", 40.42, -3.70],
    ["Opdenergy", "opdenergy.com", "DJI Enterprise · Delair", "Seville utility-scale", 37.38, -5.99],
    ["Bruc Energy", "brucenergy.com", "Wingtra", "Catalonia solar parks", 41.55, 1.52],
    ["Cox Energy", "coxenergy.com", "DJI Enterprise", "Murcia PV development", 38.00, -1.13],
    ["Capital Energy", "capitalenergy.com", "DroneDeploy", "Galicia renewables", 42.88, -8.54],
  ], SOLAR_SERVICES),
  uk: profile("uk", "solar-farms", 185, "solar farms", "95 utility · 52 rooftop · 38 agri-PV", [
    ["Lightsource bp", "lightsourcebp.com", "DJI Enterprise · DroneDeploy", "UK utility portfolio", 52.04, -0.76],
    ["ScottishPower Renewables", "scottishpowerrenewables.com", "senseFly · DJI", "Scotland solar sites", 55.86, -4.25],
    ["NextEnergy Solar", "nextenergysolarfund.com", "Wingtra", "England PV estates", 52.48, -1.90],
    ["GRIDSERVE", "gridserve.com", "DJI Enterprise", "Hybrid solar + EV hubs", 51.88, -0.42],
    ["Hive Energy", "hiveenergy.com", "DroneDeploy", "South coast PV", 50.82, -1.09],
    ["Elgin Energy", "elginenergy.co.uk", "DJI Enterprise", "NI & Scotland sites", 54.60, -5.93],
    ["BayWa r.e.", "baywa-re.com", "senseFly · Wingtra", "Wales & Midlands", 52.58, -3.78],
    ["JBM Solar", "jbmsolar.com", "DJI Enterprise", "East Anglia parks", 52.63, 1.30],
    ["Quinbrook", "quinbrook.com", "DroneDeploy", "Cleve Hill adjacent", 51.38, 0.98],
    ["Low Carbon", "lowcarbon.com", "DJI Enterprise", "Southern England PV", 51.27, -0.76],
  ], SOLAR_SERVICES),
  portugal: profile("portugal", "solar-farms", 92, "solar farms", "58 utility · 22 commercial · 12 floating", [
    ["Iberdrola Portugal", "iberdrola.pt", "DJI Enterprise · DroneDeploy", "Alentejo mega-solar", 38.02, -7.86],
    ["EDP Renováveis", "edpr.com", "senseFly · DJI", "Moura & Santiago sites", 38.15, -7.45],
    ["Galp Solar", "galp.com", "Wingtra", "Alcoutim PV cluster", 37.47, -7.47],
    ["Prosolia Energy", "prosoliaenergy.com", "DJI Enterprise", "Beja solar belt", 38.02, -7.86],
    ["Hyperion Renewables", "hyperion.pt", "DroneDeploy", "Lisbon district sites", 39.02, -8.98],
    ["Finerge", "finerge.pt", "DJI Enterprise", "Centre Portugal PV", 40.20, -8.41],
    ["Aura Power", "aurapower.com", "senseFly", "Douro solar", 41.15, -7.80],
    ["Kyon Energy", "kyonenergy.com", "Wingtra · DJI", "Alentejo development", 38.25, -7.95],
    ["WElink Energy", "welinkenergy.com", "DJI Enterprise", "Sines industrial solar", 37.95, -8.87],
    ["Sunshift", "sunshift.pt", "DroneDeploy", "Algarve commercial", 37.13, -8.02],
  ], SOLAR_SERVICES),
  kenya: profile("kenya", "solar-farms", 48, "solar farms", "22 utility · 14 C&I · 12 mini-grid", [
    ["Kenya Power (solar IPP)", "kplc.co.ke", "DJI Enterprise", "Garissa 55 MW", -0.45, 39.64],
    ["Globeleq", "globeleq.com", "DroneDeploy · DJI", "Malindi solar", -3.22, 40.12],
    ["CrossBoundary Energy", "crossboundaryenergy.com", "DJI Enterprise", "C&I rooftop portfolio", -1.29, 36.82],
    ["Norfund-backed PV", "norfund.no", "senseFly", "Turkana hybrid", 3.12, 35.60],
    ["REREC mini-grids", "rerec.co.ke", "DJI Enterprise", "Rural solar sites", -0.10, 34.75],
    ["Solarise Africa", "solariseafrica.com", "DroneDeploy", "Nairobi C&I", -1.29, 36.82],
    ["Stima Solar", "stimasolar.com", "DJI Enterprise", "Eldoret commercial", 0.51, 35.27],
    ["M-KOPA Solar", "m-kopa.com", "DJI · mobile workflows", "Western Kenya hubs", 0.04, 34.76],
    ["Azimut Energy", "azimut-energy.com", "Wingtra", "Coastal PV pipeline", -3.95, 39.75],
    ["Voltalia Kenya", "voltalia.com", "DJI Enterprise · Delair", "Kilifi development", -3.51, 39.91],
  ], SOLAR_SERVICES),
};

const CONSTRUCTION: Record<SectorCountry, SectorCountryProfile> = {
  spain: profile("spain", "construction-infrastructure", 235, "major sites", "88 highways · 62 rail civils · 85 urban", [
    ["Ferrovial", "ferrovial.com", "DJI Enterprise · DroneDeploy", "Madrid rail & road", 40.45, -3.69],
    ["Acciona Construcción", "acciona.com", "Wingtra · DJI", "Catalonia infra", 41.39, 2.17],
    ["ACS / Dragados", "grupoacs.com", "DJI Enterprise · senseFly", "National civils", 40.42, -3.70],
    ["Sacyr", "sacyr.com", "DroneDeploy", "Andalusia highways", 37.39, -5.98],
    ["FCC Construcción", "fccco.com", "DJI Enterprise", "Valencia corridor", 39.47, -0.38],
    ["OHLA", "ohla-group.com", "Wingtra", "Madrid metro civils", 40.42, -3.70],
    ["Elecnor", "elecnor.com", "DJI Enterprise · Delair", "Grid + civils", 40.45, -3.69],
    ["TYPSA", "typsa.com", "senseFly", "Engineering surveys", 40.45, -3.69],
    ["Copisa", "copisa.com", "DJI Enterprise", "Aragon infrastructure", 41.65, -0.88],
    ["Corsán-Corviam", "corsan-corviam.com", "DroneDeploy", "Galicia roads", 42.88, -8.54],
  ], CONSTRUCTION_SERVICES),
  uk: profile("uk", "construction-infrastructure", 198, "major sites", "72 highways · 48 rail · 78 building civils", [
    ["Balfour Beatty", "balfourbeatty.com", "DJI Enterprise · DroneDeploy", "HS2 & highways", 51.52, -0.12],
    ["Morgan Sindall", "morgansindall.com", "Wingtra · DJI", "National civils", 51.52, -0.12],
    ["Kier Group", "kier.co.uk", "DJI Enterprise", "Road renewals", 52.04, -0.76],
    ["Costain", "costain.com", "senseFly · DroneDeploy", "Transport agency", 51.50, -0.12],
    ["Laing O'Rourke", "laingorourke.com", "DJI Enterprise", "Major building", 51.52, -0.12],
    ["Skanska UK", "skanska.co.uk", "Wingtra", "Infrastructure", 51.52, -0.12],
    ["BAM Nuttall", "bamnuttall.co.uk", "DJI Enterprise · Delair", "Flood & rail", 51.45, -2.58],
    ["VolkerFitzpatrick", "volkerfitzpatrick.co.uk", "DroneDeploy", "Rail civils", 51.88, -0.42],
    ["Amey", "amey.co.uk", "DJI Enterprise", "Highways maintenance", 51.75, -1.26],
    ["Jacobs UK", "jacobs.com", "senseFly", "Design + survey", 51.52, -0.12],
  ], CONSTRUCTION_SERVICES),
  portugal: profile("portugal", "construction-infrastructure", 72, "major sites", "28 highways · 18 rail · 26 urban", [
    ["Mota-Engil", "mota-engil.com", "DJI Enterprise · DroneDeploy", "Lisbon metro civils", 38.72, -9.14],
    ["Teixeira Duarte", "teixeraduarte.pt", "Wingtra · DJI", "National roads", 38.72, -9.14],
    ["Somague", "somague.pt", "DJI Enterprise", "Porto infrastructure", 41.16, -8.63],
    ["Conduril", "conduril.pt", "DroneDeploy", "Alentejo highways", 38.02, -7.86],
    ["Ferrovial Portugal", "ferrovial.com", "DJI Enterprise", "Rail renewals", 38.72, -9.14],
    ["Bentley Infrastructure PT", "bentley.com", "senseFly", "Digital survey", 38.72, -9.14],
    ["Ascendi", "ascendi.pt", "DJI Enterprise · Delair", "Toll motorway ops", 39.02, -8.98],
    ["Brisa", "brisa.pt", "DroneDeploy", "Highway network", 38.72, -9.14],
    ["EFACEC Construção", "efacec.pt", "DJI Enterprise", "Energy civils", 41.16, -8.63],
    ["Martifer", "martifer.pt", "Wingtra", "Steel + infra", 39.45, -8.81],
  ], CONSTRUCTION_SERVICES),
  kenya: profile("kenya", "construction-infrastructure", 58, "major sites", "24 roads · 14 rail · 20 building", [
    ["China Road & Bridge (Kenya)", "crbc.com", "DJI Enterprise · DroneDeploy", "Nairobi expressway", -1.29, 36.82],
    ["H-Young", "hyoung.co.ke", "DJI Enterprise", "Highway packages", -1.29, 36.82],
    ["SBI International", "sbi-international.com", "Wingtra", "Urban infra", -1.29, 36.82],
    ["Kenya National Highways", "kenha.co.ke", "DroneDeploy · DJI", "National network", -1.29, 36.82],
    ["Kenya Railways", "krc.co.ke", "DJI Enterprise", "SGR corridor", -1.04, 37.08],
    ["Sinohydro Kenya", "powerchina.cn", "senseFly", "Dam & road civils", -0.10, 34.75],
    ["Crown Berger", "crownpaints.com", "DJI Enterprise", "Industrial builds", -1.29, 36.82],
    ["Architectural Association civils", "aak.or.ke", "DJI", "Public works", -1.29, 36.82],
    ["Intex Construction", "intexconstruction.co.ke", "DroneDeploy", "Commercial builds", -1.29, 36.82],
    ["Epco Builders", "epcobuilders.com", "DJI Enterprise", "Nairobi projects", -1.29, 36.82],
  ], CONSTRUCTION_SERVICES),
};

const UTILITIES: Record<SectorCountry, SectorCountryProfile> = {
  spain: profile("spain", "utilities", 88, "utility assets", "42 substations · 46 corridor zones", [
    ["Iberdrola Networks", "iberdrola.com", "DJI Enterprise · Delair", "Castile transmission", 41.65, -4.72],
    ["Endesa Distribución", "endesa.com", "senseFly · DJI", "Andalusia grid", 37.39, -5.98],
    ["Naturgy Networks", "naturgy.com", "Wingtra · DroneDeploy", "Catalonia substations", 41.39, 2.17],
    ["REE (Red Eléctrica)", "ree.es", "DJI Enterprise · Delair", "National TSO", 40.45, -3.69],
    ["E-REDES", "e-redes.pt", "DJI Enterprise", "Border grid ops", 41.55, -8.43],
    ["Viesgo Distribución", "viesgo.com", "DroneDeploy", "Northern Spain", 43.36, -5.85],
    ["I-DE (Iberdrola)", "iberdrola.com", "DJI Enterprise", "Madrid ring", 40.42, -3.70],
    ["UFD", "ufd.es", "senseFly", "Union Fenosa grid", 43.37, -8.40],
    ["EASA", "easa.es", "DJI Enterprise", "Asturias distribution", 43.36, -5.85],
    ["Viesgo RE", "viesgo.com", "Wingtra", "Renewable grid tie-in", 43.36, -5.85],
  ], UTILITIES_SERVICES),
  uk: profile("uk", "utilities", 115, "utility assets", "58 substations · 57 corridor zones", [
    ["National Grid", "nationalgrid.com", "DJI Enterprise · Delair", "England & Wales TSO", 51.52, -0.12],
    ["SSEN Transmission", "ssen.co.uk", "Wingtra · DJI", "Scotland grid", 57.15, -2.10],
    ["Northern Powergrid", "northernpowergrid.com", "DroneDeploy", "NE England", 54.98, -1.61],
    ["UK Power Networks", "ukpowernetworks.co.uk", "DJI Enterprise", "London & SE", 51.52, -0.12],
    ["Western Power", "westernpower.co.uk", "senseFly", "Wales & Midlands", 52.48, -1.90],
    ["SP Energy Networks", "spenergynetworks.co.uk", "DJI Enterprise · Delair", "Scotland & Merseyside", 55.86, -4.25],
    ["Electricity North West", "enwl.co.uk", "DroneDeploy", "NW England", 53.48, -2.24],
    ["Northern Ireland Electricity", "nienetworks.co.uk", "DJI Enterprise", "NI grid", 54.60, -5.93],
    ["Scottish Hydro", "ssen.co.uk", "Wingtra", "Highland corridors", 57.48, -4.22],
    ["Cadent Gas (aerial)", "cadentgas.com", "DJI Enterprise", "Pipeline corridors", 52.48, -1.90],
  ], UTILITIES_SERVICES),
  portugal: profile("portugal", "utilities", 48, "utility assets", "24 substations · 24 corridor zones", [
    ["REN (Redes Energéticas)", "ren.pt", "DJI Enterprise · Delair", "National TSO", 38.72, -9.14],
    ["E-REDES", "e-redes.pt", "Wingtra · DJI", "Distribution", 38.72, -9.14],
    ["EDP Distribuição", "edp.com", "DroneDeploy", "Lisbon grid", 38.72, -9.14],
    ["Galp Power", "galp.com", "DJI Enterprise", "Sines energy hub", 37.95, -8.87],
    ["Endesa Portugal", "endesa.pt", "senseFly", "Alentejo grid", 38.02, -7.86],
    ["Iberdrola Portugal Grid", "iberdrola.pt", "DJI Enterprise", "Douro corridor", 41.15, -7.80],
    ["Dourogás", "dourogas.pt", "DJI Enterprise", "Gas network", 41.16, -8.63],
    ["REN Gasodutos", "ren.pt", "Delair", "Pipeline routes", 39.45, -8.81],
    ["Goldenergy Grid", "goldenergy.pt", "DroneDeploy", "Retail + grid", 38.72, -9.14],
    ["Capwatt", "capwatt.com", "DJI Enterprise", "Cogeneration sites", 41.16, -8.63],
  ], UTILITIES_SERVICES),
  kenya: profile("kenya", "utilities", 41, "utility assets", "18 substations · 23 corridor zones", [
    ["Kenya Power", "kplc.co.ke", "DJI Enterprise · DroneDeploy", "National distribution", -1.29, 36.82],
    ["Kenya Electricity Transmission", "ketraco.co.ke", "Delair · DJI", "400 kV corridors", -1.29, 36.82],
    ["Geothermal Development", "gdc.co.ke", "Wingtra", "Olkaria grid tie-in", -0.89, 36.28],
    ["Rural Electrification", "rerec.co.ke", "DJI Enterprise", "Mini-grid rollout", -1.29, 36.82],
    ["KenGen", "kengen.co.ke", "DroneDeploy · DJI", "Seven Forks hydro", -0.65, 37.18],
    ["Lake Turkana Wind", "ltwp.co.ke", "DJI Enterprise", "Grid export line", 2.89, 36.80],
    ["Ketraco Coast", "ketraco.co.ke", "senseFly", "Mombasa substation", -4.04, 39.67],
    ["Nairobi Ring", "kplc.co.ke", "DJI Enterprise", "Urban substations", -1.29, 36.82],
    ["Kakuma mini-grid", "rerec.co.ke", "DJI", "Northern corridor", 3.72, 34.86],
    ["Isiolo solar grid", "kplc.co.ke", "DroneDeploy", "Hybrid tie-in", 0.35, 37.58],
  ], UTILITIES_SERVICES),
};

const RAIL: Record<SectorCountry, SectorCountryProfile> = {
  spain: profile("spain", "rail", 38, "rail assets", "22 corridors · 16 depots/stations", [
    ["Adif", "adif.es", "DJI Enterprise · DroneDeploy", "National rail infra", 40.42, -3.70],
    ["Renfe Operadora", "renfe.com", "DJI Enterprise", "Madrid hub", 40.42, -3.70],
    ["CAF Spain", "caf.net", "senseFly", "Rolling stock depots", 42.85, -2.67],
    ["Talgo", "talgo.com", "DJI Enterprise", "Las Rozas works", 40.50, -3.87],
    ["Ferrovial Rail", "ferrovial.com", "Wingtra · DJI", "Mediterranean corridor", 41.39, 2.17],
    ["Acciona Rail", "acciona.com", "DroneDeploy", "Madrid-Barcelona", 40.42, -3.70],
    ["Sacyr Rail", "sacyr.com", "DJI Enterprise", "Andalusia HS", 37.39, -5.98],
    ["Ineco", "ineco.com", "senseFly", "Engineering surveys", 40.45, -3.69],
    ["Metro de Madrid", "metromadrid.es", "Flyability · DJI", "Underground + depots", 40.42, -3.70],
    ["FGC Catalunya", "fgc.cat", "DJI Enterprise", "Barcelona commuter", 41.39, 2.17],
  ], RAIL_SERVICES),
  uk: profile("uk", "rail", 52, "rail assets", "28 corridors · 24 depots/stations", [
    ["Network Rail", "networkrail.co.uk", "DJI Enterprise · Delair", "National infrastructure", 51.52, -0.12],
    ["HS2 Ltd", "hs2.org.uk", "Wingtra · DroneDeploy", "Phase 1 corridor", 52.04, -0.76],
    ["Transport for London", "tfl.gov.uk", "DJI Enterprise · Flyability", "London Underground", 51.52, -0.12],
    ["ScotRail / Network Rail Scotland", "scotrail.co.uk", "senseFly", "Highland main line", 55.86, -4.25],
    ["Crossrail / Elizabeth line", "tfl.gov.uk", "DJI Enterprise", "East-west corridor", 51.52, -0.12],
    ["Northern Trains depots", "northernrailway.co.uk", "DroneDeploy", "Leeds & Manchester", 53.48, -2.24],
    ["Great Western Railway", "gwr.com", "DJI Enterprise", "Western main line", 51.45, -2.58],
    ["East Midlands Railway", "eastmidlandsrailway.co.uk", "Wingtra", "Derby depot", 52.92, -1.47],
    ["LNER", "lner.co.uk", "DJI Enterprise", "East Coast", 54.98, -1.61],
    ["Colas Rail", "colasrail.com", "DroneDeploy · DJI", "Renewals contractor", 51.52, -0.12],
  ], RAIL_SERVICES),
  portugal: profile("portugal", "rail", 24, "rail assets", "14 corridors · 10 depots", [
    ["Infraestruturas de Portugal", "infraestruturasdeportugal.pt", "DJI Enterprise · DroneDeploy", "National rail", 38.72, -9.14],
    ["CP — Comboios de Portugal", "cp.pt", "DJI Enterprise", "Lisbon hub", 38.72, -9.14],
    ["Metro do Porto", "metrodoporto.pt", "Flyability · DJI", "Porto metro", 41.16, -8.63],
    ["Metro de Lisboa", "metrolisboa.pt", "DJI Enterprise", "Underground network", 38.72, -9.14],
    ["Fertagus", "fertagus.pt", "DroneDeploy", "Tagus corridor", 38.72, -9.14],
    ["Tavira rail renewal", "infraestruturasdeportugal.pt", "Wingtra", "Algarve line", 37.13, -7.65],
    ["North corridor IP", "infraestruturasdeportugal.pt", "DJI Enterprise", "Porto–Braga", 41.55, -8.43],
    ["Sines rail link", "infraestruturasdeportugal.pt", "senseFly", "Industrial corridor", 37.95, -8.87],
    ["Beira Alta line", "infraestruturasdeportugal.pt", "DJI Enterprise", "Central Portugal", 40.64, -7.91],
    ["Alentejo freight", "cp.pt", "DroneDeploy", "Evora corridor", 38.57, -7.91],
  ], RAIL_SERVICES),
  kenya: profile("kenya", "rail", 14, "rail assets", "8 corridors · 6 depots", [
    ["Kenya Railways Corporation", "krc.co.ke", "DJI Enterprise · DroneDeploy", "SGR Nairobi–Mombasa", -1.04, 37.08],
    ["Africa Star Railway", "africastarrailway.com", "DJI Enterprise", "SGR operations", -1.04, 37.08],
    ["Rift Valley Railways legacy", "krc.co.ke", "DroneDeploy", "Metre-gauge network", -1.29, 36.82],
    ["Nairobi commuter rail", "krc.co.ke", "DJI Enterprise", "City depot", -1.29, 36.82],
    ["Mombasa port rail", "kpa.co.ke", "Wingtra", "Port link", -4.04, 39.67],
    ["Naivasha ICD", "krc.co.ke", "DJI Enterprise", "Inland container", -0.72, 36.43],
    ["Suswa freight yard", "krc.co.ke", "DroneDeploy", "SGR mid-line", -1.18, 36.32],
    ["Athi River siding", "krc.co.ke", "DJI Enterprise", "Industrial spur", -1.45, 36.98],
    ["Kisumu lake rail", "krc.co.ke", "senseFly", "Western line", -0.10, 34.75],
    ["LAPSSET rail (planned)", "lapsset.go.ke", "DJI Enterprise", "Northern corridor", 2.34, 37.98],
  ], RAIL_SERVICES),
};

const INDUSTRIAL: Record<SectorCountry, SectorCountryProfile> = {
  spain: profile("spain", "industrial-plants", 158, "industrial plants", "48 chemical · 62 energy · 48 process", [
    ["Repsol Industrial", "repsol.com", "DJI Enterprise · Flyability", "Tarragona complex", 41.12, 1.25],
    ["BASF Tarragona", "basf.com", "DJI Enterprise · Delair", "Chemical park", 41.12, 1.25],
    ["Dow Chemical Spain", "dow.com", "DroneDeploy", "Tarragona site", 41.12, 1.25],
    ["Cepsa San Roque", "cepsa.com", "DJI Enterprise", "Refinery", 36.21, -5.42],
    ["Enagas", "enagas.es", "senseFly · DJI", "LNG & pipelines", 40.45, -3.69],
    ["Iberdrola Castejón", "iberdrola.com", "Wingtra", "Combined cycle", 42.18, -1.70],
    ["Endesa As Pontes", "endesa.com", "DJI Enterprise", "Power station", 43.44, -7.85],
    ["ArcelorMittal España", "arcelormittal.com", "Flyability · DJI", "Gijón steel", 43.55, -5.67],
    ["Holcim España", "holcim.com", "DroneDeploy", "Cement plants", 40.42, -3.70],
    ["Ercros", "ercros.es", "DJI Enterprise", "Chemical sites", 41.65, -0.88],
  ], INDUSTRIAL_SERVICES),
  uk: profile("uk", "industrial-plants", 132, "industrial plants", "38 chemical · 45 energy · 49 process", [
    ["INEOS Grangemouth", "ineos.com", "DJI Enterprise · Flyability", "Scotland complex", 56.02, -3.72],
    ["BP Chemicals", "bp.com", "DJI Enterprise · Delair", "Hull & Grangemouth", 53.74, -0.33],
    ["Shell UK", "shell.co.uk", "DroneDeploy", "Stanlow refinery", 53.28, -2.84],
    ["ExxonMobil Fawley", "exxonmobil.co.uk", "DJI Enterprise", "Refinery", 50.84, -1.34],
    ["Drax Power", "drax.com", "Wingtra · DJI", "Biomass station", 53.74, -0.99],
    ["Sellafield (survey contractors)", "sellafieldsites.com", "Flyability · DJI", "Nuclear site", 54.42, -3.50],
    ["Tata Steel UK", "tatasteeleurope.com", "DJI Enterprise", "Port Talbot", 51.59, -3.78],
    ["CF Fertilisers", "cffertilisers.co.uk", "DroneDeploy", "Ince plant", 53.28, -2.84],
    ["SABIC UK", "sabic.com", "DJI Enterprise", "Teesside", 54.58, -1.18],
    ["Unilever UK manufacturing", "unilever.com", "senseFly", "National plants", 53.48, -2.24],
  ], INDUSTRIAL_SERVICES),
  portugal: profile("portugal", "industrial-plants", 44, "industrial plants", "14 chemical · 16 energy · 14 process", [
    ["Galp Sines", "galp.com", "DJI Enterprise · Flyability", "Refinery & petchem", 37.95, -8.87],
    ["Repsol Polímeros", "repsol.com", "DJI Enterprise", "Sines complex", 37.95, -8.87],
    ["EDP CCGT", "edp.com", "DroneDeploy", "Ribatejo power", 39.18, -8.45],
    ["The Navigator Company", "thenavigatorcompany.com", "Wingtra · DJI", "Figueira pulp", 40.15, -8.86],
    ["Bondalti", "bondalti.com", "DJI Enterprise", "Chemical sites", 38.72, -9.14],
    ["CUF", "cuf.pt", "senseFly", "Quimicos industriais", 38.72, -9.14],
    ["Secil Outão cement", "secil.pt", "DJI Enterprise", "Integrated plant", 38.52, -8.90],
    ["REN LNG terminal", "ren.pt", "Delair", "Sines LNG", 37.95, -8.87],
    ["Efacec manufacturing", "efacec.pt", "DroneDeploy", "Porto industrial", 41.16, -8.63],
    ["Amorim cork industrial", "amorim.com", "DJI Enterprise", "Santa Maria da Feira", 40.93, -8.54],
  ], INDUSTRIAL_SERVICES),
  kenya: profile("kenya", "industrial-plants", 32, "industrial plants", "10 chemical · 12 agri-process · 10 energy", [
    ["Kenya Pipeline Company", "kpc.co.ke", "DJI Enterprise · Delair", "Nairobi terminal", -1.29, 36.82],
    ["Bamburi Cement", "lafarge.co.ke", "DroneDeploy · DJI", "Mombasa plant", -4.04, 39.67],
    ["East African Breweries", "eabl.com", "DJI Enterprise", "Nairobi brewery", -1.29, 36.82],
    ["Kenya Breweries Ltd", "eabl.com", "Wingtra", "Ruaraka plant", -1.24, 36.88],
    ["Devki Steel", "devkigroup.com", "DJI Enterprise · Flyability", "Steel mill", -1.45, 36.98],
    ["Kapa Oil Refineries", "kapa-oil.com", "DroneDeploy", "Nairobi refinery", -1.29, 36.82],
    ["Unilever Kenya", "unilever.com", "DJI Enterprise", "Manufacturing", -1.29, 36.82],
    ["BAT Kenya", "bat.com", "senseFly", "Thika factory", -1.04, 37.08],
    ["Olkaria geothermal plants", "kengen.co.ke", "DJI Enterprise", "Energy complex", -0.89, 36.28],
    ["Muhoroni sugar complex", "chemelil.co.ke", "DroneDeploy", "Agri-industrial", -0.15, 35.20],
  ], INDUSTRIAL_SERVICES),
};

const WAREHOUSES: Record<SectorCountry, SectorCountryProfile> = {
  spain: profile("spain", "warehouses", 275, "warehouse sites", "120 logistics hubs · 95 retail DC · 60 cold chain", [
    ["Mercadona logistics", "mercadona.es", "DJI Enterprise · DroneDeploy", "Ribarroja DC", 39.55, -0.46],
    ["Amazon Spain FC", "amazon.es", "DJI Enterprise", "Barcelona FC", 41.39, 2.17],
    ["DHL Supply Chain ES", "dhl.com", "Wingtra · DJI", "Madrid hub", 40.42, -3.70],
    ["XPO Logistics Spain", "xpo.com", "DroneDeploy", "Zaragoza DC", 41.65, -0.88],
    ["FM Logistic Iberia", "fmlogistic.com", "DJI Enterprise", "Valencia hub", 39.47, -0.38],
    ["CEVA Logistics", "cevalogistics.com", "senseFly", "Barcelona port", 41.35, 2.15],
    ["Logista", "logista.com", "DJI Enterprise", "National DC network", 40.42, -3.70],
    ["El Corte Inglés logistics", "elcorteingles.es", "DroneDeploy", "Madrid DC", 40.42, -3.70],
    ["Carrefour Spain DC", "carrefour.es", "DJI Enterprise", "Seville hub", 37.39, -5.98],
    ["Prologis Spain", "prologis.com", "Wingtra", "Industrial parks", 40.42, -3.70],
  ], WAREHOUSE_SERVICES),
  uk: profile("uk", "warehouses", 365, "warehouse sites", "165 logistics hubs · 120 retail DC · 80 cold chain", [
    ["Amazon UK FC network", "amazon.co.uk", "DJI Enterprise · DroneDeploy", "Doncaster mega-DC", 53.52, -1.13],
    ["DHL UK", "dhl.co.uk", "Wingtra · DJI", "East Midlands gateway", 52.83, -1.25],
    ["XPO Logistics UK", "xpo.com", "DroneDeploy", "Southampton hub", 50.91, -1.40],
    ["Wincanton", "wincanton.co.uk", "DJI Enterprise", "National 3PL", 51.52, -0.12],
    ["GXO Logistics", "gxo.com", "senseFly", "Coventry DC", 52.41, -1.51],
    ["Royal Mail NWDC", "royalmail.com", "DJI Enterprise", "Warrington", 53.39, -2.60],
    ["Tesco DC network", "tesco.com", "DroneDeploy", "Daventry DC", 52.26, -1.16],
    ["John Lewis logistics", "johnlewis.com", "DJI Enterprise", "Milton Keynes", 52.04, -0.76],
    ["Prologis UK", "prologis.com", "Wingtra", "DIRFT Daventry", 52.33, -1.18],
    ["Segro logistics", "segro.com", "DJI Enterprise · Delair", "London logistics belt", 51.52, -0.12],
  ], WAREHOUSE_SERVICES),
  portugal: profile("portugal", "warehouses", 82, "warehouse sites", "38 logistics hubs · 28 retail DC · 16 cold chain", [
    ["DHL Portugal", "dhl.pt", "DJI Enterprise · DroneDeploy", "Lisbon hub", 38.72, -9.14],
    ["Sonae MC logistics", "sonae.pt", "DJI Enterprise", "Maia DC", 41.24, -8.62],
    ["Jerónimo Martins", "jeronymomartins.com", "DroneDeploy", "National retail DC", 38.72, -9.14],
    ["Logista Portugal", "logista.com", "Wingtra", "Distribution", 40.64, -8.64],
    ["Pingo Doce logistics", "pingodoce.pt", "DJI Enterprise", "Lisbon DC", 38.72, -9.14],
    ["Lidl Portugal DC", "lidl.pt", "senseFly", "Santo Tirso", 41.35, -8.48],
    ["Amazon Portugal", "amazon.es", "DJI Enterprise", "Lisbon fulfilment", 38.72, -9.14],
    ["CTT Expresso", "ctt.pt", "DroneDeploy", "Parcel hubs", 38.72, -9.14],
    ["Rangel Logistics", "rangel.com", "DJI Enterprise", "Porto port logistics", 41.16, -8.63],
    ["GLP Portugal", "glp.com", "Wingtra", "Industrial logistics parks", 38.72, -9.14],
  ], WAREHOUSE_SERVICES),
  kenya: profile("kenya", "warehouses", 38, "warehouse sites", "18 logistics hubs · 12 retail DC · 8 cold chain", [
    ["Bolloré Logistics Kenya", "bollore-logistics.com", "DJI Enterprise · DroneDeploy", "Mombasa port", -4.04, 39.67],
    ["Siginon Logistics", "siginon.com", "DJI Enterprise", "Nairobi ICD", -1.29, 36.82],
    ["Kenya Airways cargo", "kenya-airways.com", "DroneDeploy", "JKIA cargo", -1.32, 36.93],
    ["Twiga Foods DC", "twiga.com", "DJI Enterprise", "Nairobi fresh DC", -1.29, 36.82],
    ["Naivas distribution", "naivas.co.ke", "Wingtra", "Retail DC", -1.29, 36.82],
    ["Carrefour Kenya logistics", "carrefour.ke", "DJI Enterprise", "Nairobi hub", -1.29, 36.82],
    ["DHL Kenya", "dhl.co.ke", "DroneDeploy · DJI", "Nairobi gateway", -1.29, 36.82],
    ["Mombasa cold chain", "kpa.co.ke", "DJI Enterprise", "Port reefer zone", -4.04, 39.67],
    ["East Africa Portland DC", "eapc.co.ke", "senseFly", "Industrial storage", -1.29, 36.82],
    ["Amazon-style Jumia DC", "jumia.com", "DJI Enterprise", "E-commerce fulfilment", -1.29, 36.82],
  ], WAREHOUSE_SERVICES),
};

const AGRICULTURE: Record<SectorCountry, SectorCountryProfile> = {
  spain: profile("spain", "agriculture", 485, "large farm estates", "185 irrigated · 160 olive/vine · 140 cereal", [
    ["Grupo AN", "grupoan.com", "DJI Enterprise · DroneDeploy", "Andalusian cooperatives", 37.39, -5.98],
    ["Dcoop", "dcoop.com", "Wingtra · DJI", "Olive mega-cooperative", 37.26, -4.49],
    ["Pago de Carraovejas", "pagodecarraovejas.com", "senseFly", "Ribera del Duero", 41.65, -3.69],
    ["Castillo de Canena", "castillodecanena.com", "DJI Enterprise", "Jaén olive estates", 38.01, -3.37],
    ["García Carrión", "grupojuver.com", "DroneDeploy", "Fruit & juice estates", 39.47, -2.02],
    ["Agroponiente", "agroponiente.com", "DJI Enterprise", "Almería greenhouses", 36.84, -2.46],
    ["Sandoz / Syngenta farms", "syngenta.com", "Wingtra", "Seed production", 41.65, -0.88],
    ["Grupo Sesé agri-logistics", "gruposese.com", "DJI Enterprise", "Aragon farms", 41.65, -0.88],
    ["Ebro Foods rice", "ebrofoods.com", "DroneDeploy", "Delta del Ebro", 40.72, 0.58],
    ["Torres vineyards", "torres.es", "DJI Enterprise · senseFly", "Penedès estates", 41.48, 1.75],
  ], AGRICULTURE_SERVICES),
  uk: profile("uk", "agriculture", 295, "large farm estates", "120 arable · 85 livestock · 90 mixed", [
    ["Velcourt farming", "velcourt.com", "DJI Enterprise · DroneDeploy", "South-east estates", 51.27, 0.52],
    ["G's Fresh", "gsfresh.com", "Wingtra · DJI", "Cambridgeshire veg", 52.40, 0.12],
    ["Noble Foods", "noblefoods.co.uk", "DroneDeploy", "Egg & arable", 53.96, -1.08],
    ["Spearhead International", "spearhead-int.com", "DJI Enterprise", "East Anglia potato", 52.63, 1.30],
    ["Farmcare", "farmcare.co.uk", "senseFly", "National estates", 53.96, -1.08],
    ["Berry Gardens", "berrygardens.co.uk", "DJI Enterprise", "Kent soft fruit", 51.27, 0.52],
    ["Müller Milk farms", "muller.co.uk", "DroneDeploy", "Dairy supply chain", 52.04, -0.76],
    ["National Trust farms", "nationaltrust.org.uk", "DJI Enterprise", "Conservation estates", 50.82, -1.09],
    ["Savills rural", "savills.co.uk", "Wingtra", "Managed estates", 51.52, -0.12],
    ["Agrii crop services", "agrii.co.uk", "DJI Enterprise · DroneDeploy", "Precision ag network", 51.75, -1.26],
  ], AGRICULTURE_SERVICES),
  portugal: profile("portugal", "agriculture", 165, "large farm estates", "68 cork/oak · 52 viticulture · 45 irrigated", [
    ["Corticeira Amorim", "amorim.com", "DJI Enterprise · DroneDeploy", "Cork montados", 40.93, -8.54],
    ["Sogrape", "sogrape.com", "Wingtra · DJI", "Douro & Vinhos Verdes", 41.15, -7.80],
    ["Esporão", "esporao.com", "senseFly", "Alentejo vineyards", 38.32, -7.52],
    ["Herdade do Esporão", "esporao.com", "DJI Enterprise", "Large estate", 38.32, -7.52],
    ["RAR Agro", "raragro.pt", "DroneDeploy", "Ribatejo irrigated", 39.18, -8.45],
    ["Green Acres Alentejo", "greenacres.pt", "DJI Enterprise", "Olive & cereal", 38.02, -7.86],
    ["Frulact", "frulact.com", "Wingtra", "Fruit processing farms", 41.24, -8.62],
    ["Cofina agri holdings", "cofina.pt", "DJI Enterprise", "Mixed estates", 38.72, -9.14],
    ["Adega Cooperativa", "acv.pt", "DroneDeploy", "Vinho Verde", 41.55, -8.43],
    ["Monte da Ravasqueira", "ravasqueira.com", "DJI Enterprise", "Alentejo agri", 38.57, -7.91],
  ], AGRICULTURE_SERVICES),
  kenya: profile("kenya", "agriculture", 385, "large farm estates", "165 tea/coffee · 120 horticulture · 100 cereal", [
    ["Kakuzi", "kakuzi.com", "DJI Enterprise · DroneDeploy", "Avocado & tea estates", -0.45, 37.08],
    ["Finlays Kenya", "finlays.co.uk", "Wingtra · DJI", "Tea plantations", -0.78, 35.34],
    ["Del Monte Kenya", "freshdelmonte.com", "DroneDeploy", "Pineapple estates", -0.88, 37.12],
    ["Unilever Tea Kenya", "unilever.com", "DJI Enterprise", "Kericho tea", -0.37, 35.28],
    ["Brookside Dairy farms", "brooksidedairy.com", "senseFly", "Dairy supply", -1.29, 36.82],
    ["Kenchic poultry estates", "kenchic.com", "DJI Enterprise", "Large poultry farms", -1.29, 36.82],
    ["Flora Hollands Kenya", "royalfloraholland.com", "DroneDeploy", "Flower farms", -0.98, 36.85],
    ["Oserian flower estate", "oserian.com", "DJI Enterprise · Wingtra", "Naivasha horticulture", -0.72, 36.43],
    ["Kirinyaga rice schemes", "nib.go.ke", "DJI Enterprise", "Mwea irrigation", -0.65, 37.35],
    ["Large-scale maize estates", "kilimo.go.ke", "DroneDeploy", "Trans Nzoia", 1.05, 34.95],
  ], AGRICULTURE_SERVICES),
};

type NonMiningSector = Exclude<SectorSubSector, "mining-quarries">;

export const SECTOR_PROFILES_DATA: Record<
  SectorCountry,
  Record<NonMiningSector, SectorCountryProfile>
> = {
  spain: {
    "solar-farms": SOLAR.spain,
    "construction-infrastructure": CONSTRUCTION.spain,
    utilities: UTILITIES.spain,
    rail: RAIL.spain,
    "industrial-plants": INDUSTRIAL.spain,
    warehouses: WAREHOUSES.spain,
    agriculture: AGRICULTURE.spain,
  },
  uk: {
    "solar-farms": SOLAR.uk,
    "construction-infrastructure": CONSTRUCTION.uk,
    utilities: UTILITIES.uk,
    rail: RAIL.uk,
    "industrial-plants": INDUSTRIAL.uk,
    warehouses: WAREHOUSES.uk,
    agriculture: AGRICULTURE.uk,
  },
  portugal: {
    "solar-farms": SOLAR.portugal,
    "construction-infrastructure": CONSTRUCTION.portugal,
    utilities: UTILITIES.portugal,
    rail: RAIL.portugal,
    "industrial-plants": INDUSTRIAL.portugal,
    warehouses: WAREHOUSES.portugal,
    agriculture: AGRICULTURE.portugal,
  },
  kenya: {
    "solar-farms": SOLAR.kenya,
    "construction-infrastructure": CONSTRUCTION.kenya,
    utilities: UTILITIES.kenya,
    rail: RAIL.kenya,
    "industrial-plants": INDUSTRIAL.kenya,
    warehouses: WAREHOUSES.kenya,
    agriculture: AGRICULTURE.kenya,
  },
};